Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -27,18 +27,50 @@ jobs:
         sudo apt-get update
         sudo apt-get install -y zip unzip build-essential checkinstall zlib1g-dev wget g++ cmake make checkinstall zlib1g-dev
         sudo apt-get install libssl-dev
-
-    - name: Compile OpenSSL from source
+        
+    - name: Download and Install the latest OpenSSL
       run: |
-       sudo apt-get update
-       sudo apt-get install -y build-essential
-       wget https://www.openssl.org/source/openssl-1.1.1g.tar.gz
-       tar -xzvf openssl-1.1.1g.tar.gz
-       cd openssl-1.1.1g
-       ./config
-       make
-       sudo make install
+        # Fetch the page and list all versions
+        wget -qO- http://security.ubuntu.com/ubuntu/pool/main/o/openssl/ | grep -oP 'openssl_1\.1\.1f-1ubuntu2\.\K\d+(?=(_amd64|_i386)\.deb)' | sort -V | uniq > versions.txt
+    
+        # Extract the latest version
+        VERSION=$(tail -n 1 versions.txt)
+    
+        # Clean up
+        rm versions.txt
+    
+        # Check if we got a version
+        if [ -z "$VERSION" ]; then
+          echo "Failed to find the latest OpenSSL version."
+          exit 1
+        fi
+    
+        # Define file names
+        OPENSSL_DEB="openssl_1.1.1f-1ubuntu2.${VERSION}_amd64.deb"
+        LIBSSL_DEV_DEB="libssl-dev_1.1.1f-1ubuntu2.${VERSION}_amd64.deb"
+        LIBSSL_DEB="libssl1.1_1.1.1f-1ubuntu2.${VERSION}_amd64.deb"
+    
+        # Check and download if not cached
+        if [ ! -f "$OPENSSL_DEB" ]; then
+            wget "http://security.ubuntu.com/ubuntu/pool/main/o/openssl/$OPENSSL_DEB"
+        fi
+        if [ ! -f "$LIBSSL_DEV_DEB" ]; then
+            wget "http://security.ubuntu.com/ubuntu/pool/main/o/openssl/$LIBSSL_DEV_DEB"
+        fi
+        if [ ! -f "$LIBSSL_DEB" ]; then
+            wget "http://security.ubuntu.com/ubuntu/pool/main/o/openssl/$LIBSSL_DEB"
+        fi
+    
+        # Install the packages
+        sudo DEBIAN_FRONTEND=noninteractive dpkg -i --force-confnew $OPENSSL_DEB $LIBSSL_DEV_DEB $LIBSSL_DEB
+
+    - name: Find OpenSSL Header
+      id: find-openssl-header
+      run: |
+        HEADER_PATH=$(find /usr -name 'provider.h' 2>/dev/null | head -n 1)
+        HEADER_DIR=$(dirname "$HEADER_PATH")
+        echo "HEADER_DIR=$HEADER_DIR" >> $GITHUB_ENV
     
     - name: Compile zsign
       run: |
-        g++ *.cpp common/*.cpp -lcrypto -O3 -o zsign
+        g++ *.cpp common/*.cpp -I${HEADER_DIR} -lcrypto -O3 -o zsign
